baseurl = "/"
languageCode = "en-us"
theme = "hugo-theme-terminal"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "blog"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "orange"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 6
  favicon="favicon.ico"
  centerTheme=true

  # Show reading time in minutes for posts

  # Show table of contents at the top of your posts (defaults to false)
  # Alternatively, add this param to post front matter for specific posts
  # toc = true

  # Show full page content in RSS feed items
  #(default is Description or Summary metadata in the front matter)
  # rssFullText = true


[languages]
  [languages.en]
    title = "Berkan's Website"
    #subtitle = "based"
    keywords = ""
    #copyright = "2022 Berkan Şahin"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About me"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "proj"
        name = "Projects"
        url = "/proj"
      [[languages.en.menu.main]]
        identifier = "finals"
        name = "Final Calculators"
        url = "/finals"

    [languages.en.params.logo]
      logoText = "[bsahin.xyz ~]"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"
