name: Build and deploy to VPS

on:
  push:
    branches:
      - master  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo
        
      - name: rsync deployments
      # You may pin to the exact commit or the version.
        # uses: contention/rsync-deployments@10f98a8726e6760601d8818ea6ff812f87bf8a97
        uses: D3rHase/rsync-deploy-action@v0.2
        with:
          # Initial/required rsync flags
          # flags: -avz --delete
          # The server user
          USER: ${{ secrets.USERNAME }}
          # The deployment target
          HOST: ${{ secrets.SERVER_IP }}
          PORT: ${{ secrets.SERVER_PORT }}
          # The local path to sync
          REPOSITORY_PATH: "/public"
          # The remote path to sync
          SERVER_PATH: ${{ secrets.SERVER_DESTINATION }}
          # The private key
          PRIVATE_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}

          
        
