name: Build and deploy to VPS

on:
  push:
    branches:
      - master  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo
        

      - name: SFTP Deploy
        # You may pin to the exact commit or the version.
        # uses: wlixcc/SFTP-Deploy-Action@da88a4dbe95286266bbac3c0b2b8284048d20c8f
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          # username
          username: ${{ secrets.USERNAME }}
          # your sftp server
          server: ${{ secrets.SERVER_IP }}
          # your sftp server port, default to 22
          port: ${{ secrets.SERVER_PORT }}
          # you can copy private_key from your *.pem file, keep format
          ssh_private_key: ${{ secrets.SERVER_SSH_KEY }}
          # will put all file under this path
          local_path: "/public"
          # files will copy to under remote_path
          remote_path: ${{ secrets.SERVER_DESTINATION }}
          # connection via sftp protocol only
          #sftp_only: # optional
          # sftp args
          #sftpArgs: # optional
          # This operation will delete all files in the remote path before upload. Please be careful set this to true
          #delete_remote_files: # optional
          # SSH passsword，If a password is set, the secret key pair is ignored
          #password: # optional
          

          
        
